# build docker image and push to container registry
image: docker:dind

variables:
  DOCKER_IMAGE: irobust/simpleweb
  DOCKER_TAG: ci-1.2
  CONTAINER_NAME: simpleweb

stages:
  - build
  - deploy

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD

build_image:
  stage:
    build
  script:
    - docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
    - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}

deploy_local:
  stage:
    deploy
  script:
    - docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
    - docker run -d --rm --name $CONTAINER_NAME -p 8080:80 ${DOCKER_IMAGE}:${DOCKER_TAG}

deploy_server:
  stage:
    deploy
  script:
    - ssh -i -o StrictHostKeyChecking=no root@123.123.123.123 "
     docker pull ${DOCKER_IMAGE}:${DOCKER_TAG} &&
     docker rm -f $(docker ps -aq) &&
     docker run -d -p 8080:80 ${DOCKER_IMAGE}:${DOCKER_TAG}"
  rules:
    - when: manual